/obj/effect/spawner/lootdrop
	icon = 'icons/mob/screen_gen.dmi'
	icon_state = "x2"
	color = "#00FF00"
	var/lootcount = 1		//how many items will be spawned
	var/lootdoubles = 1		//if the same item can be spawned twice
	var/list/loot			//a list of possible items to spawn e.g. list(/obj/item, /obj/structure, /obj/effect)

/obj/effect/spawner/lootdrop/New()
	if(loot && loot.len)
		for(var/i = lootcount, i > 0, i--)
			if(!loot.len) break
			var/lootspawn = pickweight(loot)
			if(!lootdoubles)
				loot.Remove(lootspawn)

			if(lootspawn)
				new lootspawn(get_turf(src))
	qdel(src)

/obj/effect/spawner/lootdrop/armory_contraband
	name = "armory contraband gun spawner"
	lootdoubles = 0

	loot = list(
				/obj/item/weapon/gun/projectile/automatic/pistol = 8,
				/obj/item/weapon/gun/projectile/shotgun/combat = 5,
				/obj/item/weapon/gun/projectile/revolver/mateba,
				/obj/item/weapon/gun/projectile/automatic/pistol/deagle
				)

/obj/effect/spawner/lootdrop/maintenance
	name = "maintenance loot spawner"

	//How to balance this table
	//-------------------------
	//The total added weight of all the entries should be (roughly) equal to the total number of lootdrops
	//(take in account those that spawn more than one object!)
	//
	//While this is random, probabilities tells us that item distribution will have a tendency to look like
	//the content of the weighted table that created them.
	//The less lootdrops, the less even the distribution.
	//
	//If you want to give items a weight <1 you can multiply all the weights by 10
	//
	//the "" entry will spawn nothing, if you increase this value,
	//ensure that you balance it with more spawn points

	//table data:
	//-----------
	//aft maintenance: 		24 items, 18 spots 2 extra (28/08/2014)
	//asmaint: 				16 items, 11 spots 0 extra (08/08/2014)
	//asmaint2:			 	36 items, 26 spots 2 extra (28/08/2014)
	//fpmaint:				5  items,  4 spots 0 extra (08/08/2014)
	//fpmaint2:				12 items, 11 spots 2 extra (28/08/2014)
	//fsmaint:				0  items,  0 spots 0 extra (08/08/2014)
	//fsmaint2:				40 items, 27 spots 5 extra (28/08/2014)
	//maintcentral:			2  items,  2 spots 0 extra (08/08/2014)
	//port:					5  items,  5 spots 0 extra (08/08/2014)
	loot = list(
				/obj/item/bodybag = 1,
				/obj/item/clothing/glasses/meson = 2,
				/obj/item/clothing/glasses/sunglasses = 1,
				/obj/item/clothing/gloves/color/yellow/fake = 1,
				/obj/item/clothing/head/hardhat = 1,
				/obj/item/clothing/head/hardhat/red = 1,
				/obj/item/clothing/head/that{throwforce = 1; throwing = 1} = 1,
				/obj/item/clothing/head/ushanka = 1,
				/obj/item/clothing/head/welding = 1,
				/obj/item/clothing/mask/gas = 15,
				/obj/item/clothing/suit/hazardvest = 1,
				/obj/item/clothing/under/rank/vice = 1,
				/obj/item/device/assembly/prox_sensor = 4,
				/obj/item/device/assembly/timer = 3,
				/obj/item/device/flashlight = 4,
				/obj/item/device/flashlight/pen = 1,
				/obj/item/device/multitool = 2,
				/obj/item/device/radio/off = 2,
				/obj/item/device/t_scanner = 6,
				/obj/item/stack/cable_coil = 4,
				/obj/item/stack/cable_coil{amount = 5} = 6,
				/obj/item/stack/medical/bruise_pack = 1,
				/obj/item/stack/rods{amount = 10} = 9,
				/obj/item/stack/rods{amount = 23} = 1,
				/obj/item/stack/rods{amount = 50} = 1,
				/obj/item/stack/sheet/cardboard = 2,
				/obj/item/stack/sheet/metal{amount = 20} = 1,
				/obj/item/stack/sheet/mineral/plasma{layer = 2.9} = 1,
				/obj/item/stack/sheet/rglass = 1,
				/obj/item/weapon/book/manual/wiki/engineering_construction = 1,
				/obj/item/weapon/book/manual/wiki/engineering_hacking = 1,
				/obj/item/clothing/head/cone = 1,
				/obj/item/weapon/coin/silver = 1,
				/obj/item/weapon/coin/twoheaded = 1,
				/obj/item/weapon/contraband/poster = 1,
				/obj/item/weapon/crowbar = 1,
				/obj/item/weapon/crowbar/red = 1,
				/obj/item/weapon/extinguisher = 11,
				//obj/item/weapon/gun/projectile/revolver/russian = 1, //disabled until lootdrop is a proper world proc.
				/obj/item/weapon/hand_labeler = 1,
				/obj/item/weapon/paper/crumpled = 1,
				/obj/item/weapon/pen = 1,
				/obj/item/weapon/reagent_containers/spray/pestspray = 1,
				/obj/item/weapon/stock_parts/cell = 3,
				/obj/item/weapon/storage/belt/utility = 2,
				/obj/item/weapon/storage/box = 2,
				/obj/item/weapon/storage/box/cups = 1,
				/obj/item/weapon/storage/box/donkpockets = 1,
				/obj/item/weapon/storage/box/lights/mixed = 3,
				/obj/item/weapon/storage/fancy/cigarettes/dromedaryco = 1,
				/obj/item/weapon/storage/toolbox/mechanical = 1,
				/obj/item/weapon/screwdriver = 3,
				/obj/item/weapon/tank/internals/emergency_oxygen = 2,
				/obj/item/weapon/vending_refill/cola = 1,
				/obj/item/weapon/weldingtool = 3,
				/obj/item/weapon/wirecutters = 1,
				/obj/item/weapon/wrench = 4,
				/obj/item/weapon/relic = 3,
				"" = 11
				)


/obj/effect/spawner/lootdrop/crate_spawner
	name = "lootcrate spawner"
	lootdoubles = 0

	loot = list(
				/obj/structure/closet/crate/secure/loot = 20,
				"" = 80
				)

/obj/effect/spawner/lootdrop/dangerous_crate_spawner //what's a little reward without a little risk.
	name = "lootcrate spawner"
	lootdoubles = 0

	loot = list(
			/obj/structure/closet/crate/secure/loot = 30,
			/mob/living/simple_animal/hostile/mimic/crate{faction = "hostile"} = 20, //1 in 10 crates is a mimic, fun.
			/obj/structure/closet/crate/randomized/midvalue = 55,
			/obj/structure/closet/crate/randomized/highvalue = 5,
			/obj/structure/closet/crate/randomized/coin = 10,
			/obj/structure/closet/crate/randomized/toy = 10,
			/obj/structure/closet/crate/randomized/engineering = 10,
			/obj/structure/closet/crate/randomized/hydro = 10,
			/obj/structure/closet/crate/randomized/science = 10,
			/obj/structure/closet/crate/randomized/medical = 10,
			/obj/structure/closet/crate/secure/hydrosec = 10,
			/obj/structure/closet/crate/secure/plasma = 10,
			/obj/structure/closet/crate/hydroponics/prespawned = 10,
			/obj/structure/closet/crate/rcd = 10
		)

/obj/effect/spawner/lootdrop/random
	loot = list(
			/obj/item/weapon/card/data/beacon = 50,
			/obj/item/weapon/soap = 10,
			/obj/item/weapon/soap/nanotrasen = 1,
			/obj/item/weapon/soap/deluxe = 1,
			/obj/item/weapon/soap/syndie = 1,
			/obj/item/weapon/spacecash/c10 = 100,
			/obj/item/weapon/spacecash/c20 = 100,
			/obj/item/weapon/spacecash/c50 = 50,
			/obj/item/weapon/spacecash/c100 = 10,
			/obj/item/weapon/spacecash/c200 = 10,
			/obj/item/weapon/spacecash/c500 = 1,
			/obj/item/weapon/spacecash/c1000 = 1,
			/obj/item/weapon/reagent_containers/food/drinks/bottle/rum = 100,
			/obj/item/weapon/reagent_containers/food/snacks/grown/ambrosia = 100,
			/obj/item/weapon/reagent_containers/food/drinks/bottle/whiskey = 100,
			/obj/item/weapon/lighter/zippo = 100,
			/obj/item/weapon/bedsheet = 100,
			/obj/item/weapon/kitchen/utensil/knife = 100,
			/obj/item/weapon/wirecutters = 100,
			/obj/item/weapon/screwdriver = 100,
			/obj/item/weapon/weldingtool = 100,
			/obj/item/weapon/hatchet = 100,
			/obj/item/weapon/crowbar = 100,
			/obj/item/weapon/reagent_containers/glass/beaker/bluespace = 1,
			/obj/item/weapon/ore/diamond = 10,
			/obj/item/weapon/contraband/poster = 200,
			/obj/item/weapon/reagent_containers/glass/beaker/noreact = 1,
			/obj/item/seeds/cashseed = 1,
			/obj/item/weapon/melee/baton = 1,
			/obj/item/clothing/under/shorts/red = 10,
			/obj/item/clothing/under/shorts/blue = 10,
			/obj/item/clothing/under/chameleon = 1,
			/obj/item/clothing/tie/horrible = 100,
			/obj/item/weapon/melee/classic_baton = 1,
			/obj/item/toy/balloon = 10,
			/obj/item/toy/syndicateballoon = 10,
			/obj/item/weapon/pickaxe/drill = 50,
			/obj/item/device/taperecorder = 10,
			/obj/item/clothing/suit/space = 200,
			/obj/item/clothing/head/helmet/space = 200,
			/obj/item/clothing/head/kitty = 10,
			/obj/item/clothing/suit/ianshirt = 10,
			/obj/item/bluespace_crystal = 50,
			/obj/item/weapon/cane = 10,
			/obj/item/clothing/head/collectable/tophat = 10,
			/obj/item/weapon/gun/energy/plasmacutter = 10,
			/obj/item/weapon/defibrillator/compact = 10,
			/obj/item/organ/internal/brain = 50,
			/obj/item/organ/internal/brain/alien = 1,
			/obj/item/organ/internal/heart = 50,
			/obj/item/device/soulstone/anybody = 1,
			/obj/item/weapon/katana = 1,
			/obj/item/weapon/storage/backpack/clown = 1,
			/obj/item/clothing/under/rank/clown = 1,
			/obj/item/clothing/shoes/clown_shoes = 1,
			/obj/item/device/pda/clown = 1,
			/obj/item/clothing/mask/gas/clown_hat = 1,
			/obj/item/weapon/bikehorn = 1,
			/obj/item/toy/crayon/rainbow = 10,
			/obj/item/weapon/reagent_containers/spray/waterflower = 1,
			/obj/item/clothing/under/rank/mime = 1,
			/obj/item/clothing/shoes/sneakers/black = 100,
			/obj/item/device/pda/mime = 1,
			/obj/item/clothing/gloves/color/white = 100,
			/obj/item/clothing/mask/gas/mime = 1,
			/obj/item/clothing/head/beret = 1,
			/obj/item/clothing/suit/suspenders = 1,
			/obj/item/toy/crayon/mime = 1,
			/obj/item/weapon/reagent_containers/food/drinks/bottle/bottleofnothing = 10,
			/obj/item/clothing/mask/balaclava = 10,
			/obj/item/weapon/gun/projectile/automatic/pistol = 1,
			/obj/item/ammo_box/magazine/m10mm = 1,
			/obj/item/weapon/katana/cursed = 1,
			/obj/item/weapon/storage/belt/champion/wrestling = 1,
			/obj/item/clothing/mask/luchador = 10,
			/obj/item/clothing/head/bearpelt = 100,
			/obj/item/stack/sheet/metal{amount = 10} = 500,
			/obj/item/stack/sheet/glass{amount = 10} = 500,
			/obj/effect/spawner/lootdrop/random/science = 100, //spawning spawners with spawners. Have I gone too far? No.
			/obj/effect/spawner/lootdrop/random/mining = 100,
			/obj/effect/spawner/lootdrop/random/engineering = 500,
			/obj/effect/spawner/lootdrop/random/food = 100,
			/obj/effect/spawner/lootdrop/random/guns = 1,
			/obj/effect/spawner/lootdrop/random/highvalue = 1
		)

/obj/effect/spawner/lootdrop/random/highvalue
	loot = list(
			/obj/mecha/medical/odysseus = 1,
			/obj/mecha/working/ripley/mining = 1,
			/obj/mecha/working/ripley/firefighter = 1,
			/obj/item/weapon/throwing_star = 10,
			/obj/item/weapon/rcd/arcd = 10,
			/obj/item/weapon/pickaxe/drill/diamonddrill = 10,
			/obj/item/weapon/pickaxe/drill/jackhammer = 10,
			/obj/item/organ/internal/eyes/cyberimp = 10,
			/obj/item/organ/internal/cyberimp/brain/anti_drop = 10,
			/obj/item/organ/internal/cyberimp/brain/anti_stun = 10,
			/obj/item/device/firing_pin = 10,
			/obj/item/device/firing_pin/dna = 5,
			/obj/item/device/firing_pin/dna/dredd = 1,
			/obj/item/weapon/dnainjector/xraymut = 10,
			/obj/item/weapon/dnainjector/stealthmut = 10,
			/obj/item/weapon/dnainjector/telemut = 10,
			/obj/item/weapon/dnainjector/chameleonmut = 10,
			/obj/effect/spawner/lootdrop/random/guns = 10
		)
/obj/effect/spawner/lootdrop/random/booze
	loot = list(
			/obj/item/weapon/reagent_containers/food/drinks/bottle/bottleofnothing = 1,
			/obj/item/weapon/reagent_containers/food/drinks/bottle/cognac = 10,
			/obj/item/weapon/reagent_containers/food/drinks/bottle/gin = 10,
			/obj/item/weapon/reagent_containers/food/drinks/bottle/kahlua = 1,
			/obj/item/weapon/reagent_containers/food/drinks/bottle/patron = 10,
			/obj/item/weapon/reagent_containers/food/drinks/bottle/rum = 10,
			/obj/item/weapon/reagent_containers/food/drinks/bottle/tequila = 10,
			/obj/item/weapon/reagent_containers/food/drinks/bottle/vermouth = 10,
			/obj/item/weapon/reagent_containers/food/drinks/bottle/vodka = 30,
			/obj/item/weapon/reagent_containers/food/drinks/bottle/vodka/badminka = 1,
			/obj/item/weapon/reagent_containers/food/drinks/bottle/whiskey = 1,
			/obj/item/weapon/reagent_containers/food/drinks/bottle/wine = 10,
			/obj/item/weapon/reagent_containers/food/drinks/beer = 10,
			/obj/item/weapon/reagent_containers/food/drinks/ale = 10
	)

/obj/effect/spawner/lootdrop/random/mining
	loot = list(
			/obj/item/weapon/strangerock = 10000,
			/obj/item/weapon/pickaxe = 10000,
			/obj/item/weapon/pickaxe/diamond = 10,
			/obj/item/weapon/pickaxe/drill = 100,
			/obj/item/weapon/pickaxe/drill/diamonddrill = 1,
			/obj/item/weapon/pickaxe/excavationdrill = 100,
			/obj/item/weapon/ore/uranium = 10,
			/obj/item/weapon/ore/iron = 10000,
			/obj/item/weapon/ore/glass = 10000,
			/obj/item/weapon/ore/plasma = 100,
			/obj/item/weapon/ore/silver = 100,
			/obj/item/weapon/ore/gold = 100,
			/obj/item/weapon/ore/diamond = 1,
			/obj/item/weapon/ore/bananium = 1,
			/obj/item/weapon/mining_bait = 10000,
			/obj/item/weapon/mining_voucher = 10,
			/obj/item/weapon/storage/belt/mining = 5000,
			/obj/item/weapon/storage/backpack/satchel_eng = 5000,
			/obj/structure/ore_box = 1000,
			/obj/item/device/mining_scanner = 10000,
			/obj/item/device/mining_charge = 100

		)
/obj/effect/spawner/lootdrop/random/engineering
	loot = list(
			/obj/item/stack/sheet/metal{amount = 10} = 500,
			/obj/item/stack/sheet/glass{amount = 10} = 500,
			/obj/item/weapon/rcd = 10,
			/obj/item/weapon/rcd/arcd = 1,
			/obj/item/weapon/rcd_ammo = 10,
			/obj/item/weapon/rcd_ammo/large = 1,
			/obj/item/weapon/wrench = 100,
			/obj/item/weapon/screwdriver = 100,
			/obj/item/weapon/wirecutters = 100,
			/obj/item/weapon/weldingtool = 100,
			/obj/item/weapon/weldingtool/largetank = 10,
			/obj/item/weapon/weldingtool/hugetank = 1,
			/obj/item/weapon/weldingtool/experimental = 1,
			/obj/item/weapon/weldingtool/mini = 10,
			/obj/item/weapon/crowbar = 100,
			/obj/item/weapon/crowbar/red = 10,
			/obj/item/weapon/crowbar/large = 10,
			/obj/item/weapon/airlock_electronics = 100,
			/obj/item/weapon/airalarm_electronics = 100,
			/obj/item/apc_frame = 100,
			/obj/item/device/analyzer = 100,
			/obj/item/device/electropack = 100,
			/obj/item/device/flashlight = 100,
			/obj/item/device/flashlight/lamp/bananalamp = 1,
			/obj/item/device/flashlight/lamp/green = 100,
			/obj/item/device/flashlight/seclite = 10,
			/obj/item/device/multitool = 100,
			/obj/item/device/assembly/igniter = 100,
			/obj/item/device/assembly/timer = 100,
			/obj/item/device/assembly/signaler = 100,
			/obj/item/device/assembly/infra = 100,
			/obj/item/device/assembly/prox_sensor = 100,
			/obj/item/device/assembly/voice = 1,
			/obj/item/device/lightreplacer = 10,
			/obj/item/weapon/stock_parts/cell/high = 100,
			/obj/item/weapon/storage/part_replacer = 1,
			/obj/item/weapon/storage/belt/utility = 10,
			/obj/item/weapon/storage/toolbox/electrical = 100,
			/obj/item/weapon/storage/toolbox/mechanical = 100
		)

/obj/effect/spawner/lootdrop/random/guns
	loot = list(
			/obj/item/weapon/gun/energy/laser = 1,
			/obj/item/weapon/gun/energy/laser/practice = 1,
			/obj/item/weapon/gun/energy/laser/retro = 1,
			/obj/item/weapon/gun/energy/laser/scatter = 1,
			/obj/item/weapon/gun/energy/lasercannon = 1,
			/obj/item/weapon/gun/energy/xray = 1,
			/obj/item/weapon/gun/projectile/automatic/proto = 1,
			/obj/item/weapon/gun/projectile/automatic/c20r = 1,
			/obj/item/weapon/gun/projectile/automatic/c20r/unrestricted = 1,
			/obj/item/weapon/gun/projectile/automatic/wt550 = 1,
			/obj/item/weapon/gun/projectile/automatic/l6_saw = 1,
			/obj/item/weapon/gun/projectile/automatic/l6_saw/unrestricted = 1,
			/obj/item/weapon/gun/projectile/automatic/m90 = 1,
			/obj/item/weapon/gun/projectile/automatic/tommygun = 1,
			/obj/item/weapon/gun/projectile/automatic/mini_uzi = 1,
			/obj/item/weapon/gun/projectile/automatic/ar = 1,
			/obj/item/weapon/gun/projectile/revolver/detective = 1,
			/obj/item/weapon/gun/projectile/revolver/mateba = 1,
			/obj/item/weapon/gun/projectile/revolver/russian = 1,
			/obj/item/weapon/gun/projectile/revolver/russian/polish = 1,
			/obj/item/weapon/gun/projectile/revolver/doublebarrel = 1,
			/obj/item/weapon/gun/projectile/revolver/doublebarrel/improvised = 1,
			/obj/item/weapon/gun/projectile/shotgun/combat = 1,
			/obj/item/weapon/gun/projectile/shotgun/boltaction = 1,
			/obj/item/weapon/gun/projectile/shotgun/riot = 1,
			/obj/item/weapon/gun/projectile/shotgun/sc_pump = 1,
			/obj/item/weapon/gun/syringe = 1,
			/obj/item/weapon/gun/syringe/rapidsyringe = 1,
			/obj/item/ammo_box/a357 = 1,
			/obj/item/ammo_box/c38 = 1,
			/obj/item/ammo_box/c9mm = 1,
			/obj/item/ammo_box/c10mm = 1,
			/obj/item/ammo_box/c45 = 1,
			/obj/item/ammo_box/a40mm = 1,
			/obj/item/ammo_box/a762 = 1
		)

/obj/effect/spawner/lootdrop/random/science
	loot = list(
			/obj/item/weapon/storage/part_replacer = 100,
			/obj/item/bluespace_crystal/artificial = 1,
			/obj/item/weapon/circuitboard/advanced_security = 1,
			/obj/item/weapon/circuitboard/turbine_computer = 10,
			/obj/item/weapon/circuitboard/telesci_console = 100,
			/obj/item/weapon/circuitboard/security = 10,
			/obj/item/weapon/circuitboard/aicore = 1,
			/obj/item/weapon/circuitboard/aiupload = 1,
			/obj/item/weapon/circuitboard/borgupload = 1,
			/obj/item/weapon/circuitboard/med_data = 100,
			/obj/item/weapon/circuitboard/pandemic = 100,
			/obj/item/weapon/circuitboard/scan_consolenew = 100,
			/obj/item/weapon/circuitboard/communications = 1,
			/obj/item/weapon/circuitboard/card = 1,
			/obj/item/weapon/circuitboard/teleporter = 100,
			/obj/item/weapon/circuitboard/secure_data = 1,
			/obj/item/weapon/circuitboard/stationalert = 10,
			/obj/item/weapon/circuitboard/air_management = 10,
			/obj/item/weapon/circuitboard/injector_control = 10,
			/obj/item/weapon/circuitboard/atmos_alert = 10,
			/obj/item/weapon/circuitboard/pod = 100,
			/obj/item/weapon/circuitboard/robotics = 100,
			/obj/item/weapon/circuitboard/cloning = 10,
			/obj/item/weapon/circuitboard/arcade/battle = 100,
			/obj/item/weapon/circuitboard/arcade/orion_trail = 100,
			/obj/item/weapon/circuitboard/turbine_control = 10,
			/obj/item/weapon/circuitboard/solar_control = 10,
			/obj/item/weapon/circuitboard/powermonitor = 10,
			/obj/item/weapon/circuitboard/prisoner = 1,
			/obj/item/weapon/circuitboard/rdconsole = 10,
			/obj/item/weapon/circuitboard/mecha_control = 10,
			/obj/item/weapon/circuitboard/rdservercontrol = 10,
			/obj/item/weapon/circuitboard/crew = 100,
			/obj/item/weapon/circuitboard/mech_bay_power_console = 10,
			/obj/item/weapon/circuitboard/operating = 10,
			/obj/item/weapon/circuitboard/mining = 10,
			/obj/item/weapon/circuitboard/comm_monitor = 10,
			/obj/item/weapon/circuitboard/comm_server = 10,
			/obj/item/weapon/circuitboard/aifixer = 10,
			/obj/item/weapon/circuitboard/area_atmos = 10,
			/obj/item/weapon/circuitboard/slot_machine = 100,
			/obj/item/weapon/circuitboard/libraryconsole = 100,
			/obj/item/weapon/storage/box/monkeycubes = 100,
			/obj/item/weapon/storage/box/emps = 1,
			/obj/item/weapon/storage/box/injectors = 10,
			/obj/item/weapon/stock_parts/console_screen = 100,
			/obj/item/weapon/stock_parts/capacitor = 100,
			/obj/item/weapon/stock_parts/scanning_module = 100,
			/obj/item/weapon/stock_parts/manipulator = 100,
			/obj/item/weapon/stock_parts/micro_laser = 100,
			/obj/item/weapon/stock_parts/matter_bin = 100,
			/obj/item/weapon/stock_parts/capacitor/adv = 10,
			/obj/item/weapon/stock_parts/scanning_module/adv = 10,
			/obj/item/weapon/stock_parts/manipulator/nano = 10,
			/obj/item/weapon/stock_parts/micro_laser/high = 10,
			/obj/item/weapon/stock_parts/matter_bin/adv = 10,
			/obj/item/weapon/stock_parts/capacitor/super = 2,
			/obj/item/weapon/stock_parts/scanning_module/phasic = 2,
			/obj/item/weapon/stock_parts/manipulator/pico = 2,
			/obj/item/weapon/stock_parts/micro_laser/ultra = 2,
			/obj/item/weapon/stock_parts/matter_bin/super = 2,
			/obj/item/weapon/stock_parts/capacitor/quadratic = 1,
			/obj/item/weapon/stock_parts/scanning_module/triphasic = 1,
			/obj/item/weapon/stock_parts/manipulator/femto = 1,
			/obj/item/weapon/stock_parts/micro_laser/quadultra = 1,
			/obj/item/weapon/stock_parts/matter_bin/bluespace = 1,
			/obj/effect/spawner/lootdrop/random/techdisks = 20,
			/obj/effect/spawner/lootdrop/random/designdisks = 20
			)

/obj/effect/spawner/lootdrop/random/techdisks
	loot = list(
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/materials{level = 2}} = 100,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/materials{level = 3}} = 70,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/materials{level = 4}} = 30,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/materials{level = 5}} = 5,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/materials{level = 6}} = 1,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/engineering{level = 2}} = 100,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/engineering{level = 3}} = 70,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/engineering{level = 4}} = 30,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/engineering{level = 5}} = 5,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/engineering{level = 6}} = 1,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/plasmatech{level = 2}} = 100,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/plasmatech{level = 3}} = 70,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/plasmatech{level = 4}} = 30,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/plasmatech{level = 5}} = 5,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/plasmatech{level = 6}} = 1,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/powerstorage{level = 2}} = 100,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/powerstorage{level = 3}} = 70,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/powerstorage{level = 4}} = 30,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/powerstorage{level = 5}} = 5,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/powerstorage{level = 6}} = 1,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/bluespace{level = 2}} = 100,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/bluespace{level = 3}} = 70,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/bluespace{level = 4}} = 301,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/bluespace{level = 5}} = 5,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/bluespace{level = 6}} = 1,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/biotech{level = 2}} = 100,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/biotech{level = 3}} = 70,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/biotech{level = 4}} = 30,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/biotech{level = 5}} = 5,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/biotech{level = 6}} = 1,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/combat{level = 2}} = 100,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/combat{level = 3}} = 70,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/combat{level = 4}} = 30,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/combat{level = 5}} = 5,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/combat{level = 6}} = 1,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/magnets{level = 2}} = 100,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/magnets{level = 3}} = 70,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/magnets{level = 4}} = 30,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/magnets{level = 5}} = 5,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/magnets{level = 6}} = 1,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/programming{level = 2}} = 100,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/programming{level = 3}} = 70,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/programming{level = 4}} = 30,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/programming{level = 5}} = 5,
			/obj/item/weapon/disk/tech_disk{stored = new /datum/tech/programming{level = 6}} = 1
		)

/obj/effect/spawner/lootdrop/random/designdisks
	loot = list(
			/obj/item/weapon/disk/design_disk{blueprint = new /datum/design/drill} = 1000,
			/obj/item/weapon/disk/design_disk{blueprint = new /datum/design/plasmacutter} = 100,
			/obj/item/weapon/disk/design_disk{blueprint = new /datum/design/plasmacutter_adv} = 10,
			/obj/item/weapon/disk/design_disk{blueprint = new /datum/design/jackhammer} = 10,
			/obj/item/weapon/disk/design_disk{blueprint = new /datum/design/drill_diamond} = 1,
			/obj/item/weapon/disk/design_disk{blueprint = new /datum/design/beacon} = 100,
			/obj/item/weapon/disk/design_disk{blueprint = new /datum/design/bag_holding} = 1,
			/obj/item/weapon/disk/design_disk{blueprint = new /datum/design/belt_holding} = 1,
			/obj/item/weapon/disk/design_disk{blueprint = new /datum/design/bluespace_crystal} = 10,
			/obj/item/weapon/disk/design_disk{blueprint = new /datum/design/bluespace_crystal2} = 1,
			/obj/item/weapon/disk/design_disk{blueprint = new /datum/design/telesci_gps} = 1000,
			/obj/item/weapon/disk/design_disk{blueprint = new /datum/design/miningsatchel_holding} = 1,
			/obj/item/weapon/disk/design_disk{blueprint = new /datum/design/health_hud} = 1000,
			/obj/item/weapon/disk/design_disk{blueprint = new /datum/design/security_hud} = 1000,
			/obj/item/weapon/disk/design_disk{blueprint = new /datum/design/security_hud_night} = 10,
			/obj/item/weapon/disk/design_disk{blueprint = new /datum/design/welding_mask} = 100,
			/obj/item/weapon/disk/design_disk{blueprint = new /datum/design/air_horn} = 1,
			/obj/item/weapon/disk/design_disk{blueprint = new /datum/design/mesons} = 1000,
			/obj/item/weapon/disk/design_disk{blueprint = new /datum/design/engine_goggles} = 100,
			/obj/item/weapon/disk/design_disk{blueprint = new /datum/design/nvgmesons} = 1,
			/obj/item/weapon/disk/design_disk{blueprint = new /datum/design/night_vision_goggles} = 10,
			/obj/item/weapon/disk/design_disk{blueprint = new /datum/design/magboots} = 1000,
			/obj/item/weapon/disk/design_disk{blueprint = new /datum/design/buffer} = 1000,
			/obj/item/weapon/disk/design_disk{blueprint = new /datum/design/holosign} = 1000,
			/obj/item/weapon/disk/design_disk{blueprint = new /datum/design/exwelder} = 10,
			/obj/item/weapon/disk/design_disk{blueprint = new /datum/design/arcd} = 10,
			/obj/item/weapon/disk/design_disk{blueprint = new /datum/design/arcd_ammo} = 10
		)

/obj/effect/spawner/lootdrop/random/food
	loot = list(
			/obj/item/weapon/reagent_containers/food/snacks/burger = 1,
			/obj/item/weapon/reagent_containers/food/snacks/burger/plain = 1,
			/obj/item/weapon/reagent_containers/food/snacks/burger/human = 1,
			/obj/item/weapon/reagent_containers/food/snacks/burger/corgi = 1,
			/obj/item/weapon/reagent_containers/food/snacks/burger/fish = 1,
			/obj/item/weapon/reagent_containers/food/snacks/burger/appendix = 1,
			/obj/item/weapon/reagent_containers/food/snacks/burger/tofu = 1,
			/obj/item/weapon/reagent_containers/food/snacks/burger/roburger = 1,
			/obj/item/weapon/reagent_containers/food/snacks/burger/roburgerbig = 1,
			/obj/item/weapon/reagent_containers/food/snacks/burger/xeno = 1,
			/obj/item/weapon/reagent_containers/food/snacks/burger/clown = 1,
			/obj/item/weapon/reagent_containers/food/snacks/burger/mime = 1,
			/obj/item/weapon/reagent_containers/food/snacks/burger/brain = 1,
			/obj/item/weapon/reagent_containers/food/snacks/burger/bearger = 1,
			/obj/item/weapon/reagent_containers/food/snacks/burger/ghost = 1,
			/obj/item/weapon/reagent_containers/food/snacks/burger/red = 1,
			/obj/item/weapon/reagent_containers/food/snacks/burger/jelly/slime = 1,
			/obj/item/weapon/reagent_containers/food/snacks/burger/fivealarm = 1,
			/obj/item/weapon/reagent_containers/food/snacks/burger/rat = 1,
			/obj/item/weapon/reagent_containers/food/snacks/burger/lingseek = 1,
			/obj/item/weapon/reagent_containers/food/snacks/burger/lingseek_big = 1,
			/obj/item/weapon/reagent_containers/food/snacks/burger/meatseek = 1,
			/obj/item/weapon/reagent_containers/food/snacks/cheesewheel = 1,
			/obj/item/weapon/reagent_containers/food/snacks/cheesewedge = 1,
			/obj/item/weapon/reagent_containers/food/snacks/candy_corn = 1,
			/obj/item/weapon/reagent_containers/food/snacks/chocolatebar = 1,
			/obj/item/weapon/reagent_containers/food/snacks/butterbar = 1,
			/obj/item/weapon/reagent_containers/food/snacks/fries = 1,
			/obj/item/weapon/reagent_containers/food/snacks/soydope = 1,
			/obj/item/weapon/reagent_containers/food/snacks/cheesyfries = 1,
			/obj/item/weapon/reagent_containers/food/snacks/carrotfries = 1,
			/obj/item/weapon/reagent_containers/food/snacks/candiedapple = 1,
			/obj/item/weapon/reagent_containers/food/snacks/mint = 1,
			/obj/item/weapon/reagent_containers/food/snacks/wrap = 1,
			/obj/item/weapon/reagent_containers/food/snacks/spidereggs = 1,
			/obj/item/weapon/reagent_containers/food/snacks/beans = 1,
			/obj/item/weapon/reagent_containers/food/snacks/chococoin = 1,
			/obj/item/weapon/reagent_containers/food/snacks/chocoorange = 1,
			/obj/item/weapon/reagent_containers/food/snacks/eggplantparm = 1,
			/obj/item/weapon/reagent_containers/food/snacks/tortilla = 1,
			/obj/item/weapon/reagent_containers/food/snacks/burrito = 1,
			/obj/item/weapon/reagent_containers/food/snacks/cheesyburrito = 1,
			/obj/item/weapon/reagent_containers/food/snacks/carneburrito = 1,
			/obj/item/weapon/reagent_containers/food/snacks/fuegoburrito = 1,
			/obj/item/weapon/reagent_containers/food/snacks/yakiimo = 1,
			/obj/item/weapon/reagent_containers/food/snacks/roastparsnip = 1,
			/obj/item/weapon/reagent_containers/food/snacks/melonfruitbowl = 1,
			/obj/item/weapon/reagent_containers/food/snacks/spacefreezy = 1,
			/obj/item/weapon/reagent_containers/food/snacks/sundae = 1,
			/obj/item/weapon/reagent_containers/food/snacks/honkdae = 1,
			/obj/item/weapon/reagent_containers/food/snacks/nachos = 1,
			/obj/item/weapon/reagent_containers/food/snacks/cheesynachos = 1,
			/obj/item/weapon/reagent_containers/food/snacks/cubannachos = 1,
			/obj/item/weapon/reagent_containers/food/snacks/melonkeg = 1,
			/obj/item/weapon/reagent_containers/food/snacks/pizza = 1,
			/obj/item/weapon/reagent_containers/food/snacks/pizzaslice = 10,
			/obj/item/weapon/reagent_containers/food/snacks/pizza/margherita = 1,
			/obj/item/weapon/reagent_containers/food/snacks/pizza/meatpizza = 1,
			/obj/item/weapon/reagent_containers/food/snacks/pizzaslice/margherita = 10,
			/obj/item/weapon/reagent_containers/food/snacks/pizzaslice/meatpizza = 10,
			/obj/item/weapon/reagent_containers/food/snacks/pizza/mushroompizza = 1,
			/obj/item/weapon/reagent_containers/food/snacks/pizzaslice/mushroompizza = 10,
			/obj/item/weapon/reagent_containers/food/snacks/pizza/vegetablepizza = 1,
			/obj/item/weapon/reagent_containers/food/snacks/pizzaslice/vegetablepizza = 10,
			/obj/item/weapon/reagent_containers/food/snacks/pizza/donkpocket = 1,
			/obj/item/weapon/reagent_containers/food/snacks/pizzaslice/donkpocket = 10,
			/obj/item/weapon/reagent_containers/food/snacks/pizza/dank = 1,
			/obj/item/weapon/reagent_containers/food/snacks/pizzaslice/dank = 1,
			/obj/item/weapon/reagent_containers/food/snacks/pizza/sassysage = 1,
			/obj/item/weapon/reagent_containers/food/snacks/pizzaslice/sassysage = 10,
			/obj/item/weapon/reagent_containers/food/snacks/donut/chaos = 1
		)


	/obj/effect/spawner/lootdrop/random/seeds
		loot = list(
			/obj/item/seeds/chiliseed = 100,
			/obj/item/seeds/replicapod = 100,
			/obj/item/seeds/grapeseed = 100,
			/obj/item/seeds/cabbageseed = 100,
			/obj/item/seeds/greengrapeseed = 100,
			/obj/item/seeds/berryseed = 100,
			/obj/item/seeds/glowberryseed = 100,
			/obj/item/seeds/bananaseed = 100,
			/obj/item/seeds/mimanaseed = 100,
			/obj/item/seeds/eggplantseed = 100,
			/obj/item/seeds/eggyseed = 100,
			/obj/item/seeds/bloodtomatoseed = 10,
			/obj/item/seeds/tomatoseed = 100,
			/obj/item/seeds/killertomatoseed = 100,
			/obj/item/seeds/bluetomatoseed = 10,
			/obj/item/seeds/bluespacetomatoseed = 1,
			/obj/item/seeds/cornseed = 100,
			/obj/item/seeds/snapcornseed = 100,
			/obj/item/seeds/poppyseed = 100,
			/obj/item/seeds/geraniumseed = 10,
			/obj/item/seeds/lilyseed = 100,
			/obj/item/seeds/potatoseed = 100,
			/obj/item/seeds/sweetpotatoseed = 10,
			/obj/item/seeds/icepepperseed = 10,
			/obj/item/seeds/soyaseed = 100,
			/obj/item/seeds/koiseed = 100,
			/obj/item/seeds/wheatseed = 100,
			/obj/item/seeds/oatseed = 100,
			/obj/item/seeds/riceseed = 100,
			/obj/item/seeds/parsnipseed = 100,
			/obj/item/seeds/carrotseed = 100,
			/obj/item/seeds/reishimycelium = 100,
			/obj/item/seeds/amanitamycelium = 100,
			/obj/item/seeds/angelmycelium = 100,
			/obj/item/seeds/libertymycelium = 100,
			/obj/item/seeds/chantermycelium = 100,
			/obj/item/seeds/towermycelium = 100,
			/obj/item/seeds/steelmycelium = 100,
			/obj/item/seeds/glowshroom = 100,
			/obj/item/seeds/plumpmycelium = 100,
			/obj/item/seeds/walkingmushroommycelium = 1,
			/obj/item/seeds/nettleseed = 100,
			/obj/item/seeds/deathnettleseed = 10,
			/obj/item/seeds/weeds = 100,
			/obj/item/seeds/harebell = 100,
			/obj/item/seeds/sunflowerseed = 100,
			/obj/item/seeds/moonflowerseed = 1,
			/obj/item/seeds/novaflowerseed = 1,
			/obj/item/seeds/appleseed = 100,
			/obj/item/seeds/poisonedappleseed = 10,
			/obj/item/seeds/goldappleseed = 1,
			/obj/item/seeds/ambrosiavulgarisseed = 100,
			/obj/item/seeds/ambrosiadeusseed = 10,
			/obj/item/seeds/whitebeetseed = 100,
			/obj/item/seeds/redbeetseed = 100,
			/obj/item/seeds/sugarcaneseed = 100,
			/obj/item/seeds/watermelonseed = 100,
			/obj/item/seeds/holymelonseed = 10,
			/obj/item/seeds/pumpkinseed = 100,
			/obj/item/seeds/blumpkinseed = 10,
			/obj/item/seeds/limeseed = 100,
			/obj/item/seeds/lemonseed = 100,
			/obj/item/seeds/cashseed = 100,
			/obj/item/seeds/orangeseed = 100,
			/obj/item/seeds/poisonberryseed = 10,
			/obj/item/seeds/grassseed = 100,
			/obj/item/seeds/deathberryseed = 100,
			/obj/item/seeds/carpetseed = 10,
			/obj/item/seeds/cocoapodseed = 100,
			/obj/item/seeds/vanillapodseed = 10,
			/obj/item/seeds/cherryseed = 100,
			/obj/item/seeds/bluecherryseed = 10,
			/obj/item/seeds/kudzuseed = 10,
			/obj/item/seeds/chilighost = 10,
			/obj/item/seeds/gatfruit = 1,
			/obj/item/seeds/coffee_arabica_seed = 100,
			/obj/item/seeds/coffee_robusta_seed = 10,
			/obj/item/seeds/tobacco_seed = 100,
			/obj/item/seeds/tobacco_space_seed = 10,
			/obj/item/seeds/tea_aspera_seed = 100,
			/obj/item/seeds/tea_astra_seed = 10
		)